import { Component } from '@angular/core';
import { Character } from '../../models/character';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss'],
})
export class ProductsComponent {
  character: Array<Character>= [
    {
      id: 1,
      name: 'Sasuke',
      clan: 'Uchiha',
      affiliation: [' Konohagakure', ' Otogakure', ' Ryūchi Cave', ' Akatsuki'],
      mainAffiliation: 'konoha',
      nature: [' Lightning', ' Fire', ' Wind', ' Earth', ' Water'],
      patent: 'Genin',
      mission: 34,
      kill: 85,
      img: 'https://vignette.wikia.nocookie.net/naruto/images/9/99/Sasuke_Uchiha_(Akatsuki).PNG/revision/latest?cb=20150126182611&path-prefix=pt-br',
    },
    {
      id: 2,
      name: 'Kakashi',
      clan: 'Hatake',
      affiliation: [' Konohagakure', ' Root', ' Allied Shinobi Forces'],
      mainAffiliation: 'konoha',
      nature: [' Lightning', ' Fire', ' Wind', ' Earth', ' Water'],
      patent: 'Hokage',
      mission: 571,
      kill: 1298,
      img: 'http://4.bp.blogspot.com/-T_GwICvZRHo/ULlr246kU-I/AAAAAAAAAxM/qr1dbneTOAg/s1600/moe-34393-hatake_kakashi-male-naruto.png',
    },
    {
      id: 3,
      name: 'Obito',
      clan: 'Uchiha',
      affiliation: [' Konohagakure', ' Akatsuki', ' Kirigakure'],
      mainAffiliation: 'konoha',
      nature: [' Lightning', ' Fire', ' Wind', ' Earth', ' Water', ' Wood'],
      patent: 'Chunin',
      mission: 47,
      kill: 1284,
      img: 'https://vignette2.wikia.nocookie.net/naruto/images/3/31/Obito_Jinch%C5%ABriki_%28Render%29.png/revision/latest?cb=20150519212703&path-prefix=pt-br',
    },
    {
      id: 4,
      name: 'Naruto',
      clan: 'Uzumaki',
      affiliation: [
        ' Konohagakure',
        ' Mount Myōboku',
        ' Allied Shinobi Forces',
      ],
      mainAffiliation: 'konoha',
      nature: [' Lightning', ' Fire', ' Wind', ' Earth', ' Water', ' Wood'],
      patent: 'Hokage',
      mission: 247,
      kill: 70,
      img: 'http://clipart-library.com/img/419043.png',
    },
    {
      id: 5,
      name: 'Kurotsuchi',
      clan: 'Kamizuru',
      affiliation: [' Iwagakure', ' Allied Shinobi Forces'],
      mainAffiliation: 'iwa',
      nature: [' Fire', ' Earth', ' Water'],
      patent: 'Tsuchikage',
      mission: 742,
      kill: 148,
      img: 'https://vignette.wikia.nocookie.net/naruto/images/0/06/Kurotsuchi_Tsuchikage_(Render).png/revision/latest?cb=20160706005814&path-prefix=pt-br',
    },
    {
      id: 6,
      name: 'Shikamaru',
      clan: 'Nara',
      affiliation: [' Konohagakure', ' Allied Shinobi Forces'],
      mainAffiliation: 'konoha',
      nature: [' Fire', ' Earth'],
      patent: 'Jonin',
      mission: 428,
      kill: 75,
      img: 'https://i.pinimg.com/originals/eb/80/28/eb802879ce1b254ca7b43ea7c94bb421.png',
    },
    {
      id: 7,
      name: 'Suigetsu',
      clan: 'Hōzuki',
      affiliation: [' Kirigakure', ' Otogakure', ' Akatsuki'],
      mainAffiliation: 'kiri',
      nature: [' Wind', ' Water'],
      patent: 'Genin',
      mission: 49,
      kill: 173,
      img: 'http://img2.wikia.nocookie.net/__cb20120522132903/denaruto3/de/images/8/8d/Suigetsu_profil.png',
    },
    {
      id: 8,
      name: 'Yagura',
      clan: 'Karatachi',
      affiliation: [' Kirigakure'],
      mainAffiliation: 'kiri',
      nature: [' Wind', ' Water'],
      patent: 'Mizukage',
      mission: 579,
      kill: 879,
      img: 'https://i.pinimg.com/originals/4c/72/e0/4c72e05acba1195e939cf3deb19664f6.png',
    },
  ];
}
